[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "php83Packages.composer",
]

[phases.install]
cmds = [
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader",
]

[phases.build]
cmds = [
  "COMPOSER_ALLOW_SUPERUSER=1 composer require lucascudo/laravel-pt-br-localization --no-scripts",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
